# ✅ Chargement des contrôleurs avec les attributs
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# ✅ Route pour la déconnexion automatique (logout)
_security_logout:
    resource: security.route_loader.logout
    type: service

# ✅ Inclusion d’un autre fichier YAML (routes/security.yaml)
import_security_routes:
    resource: routes/security.yaml
    type: yaml
